### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Justinnng** [ycwalker/CMS-of-Blog#14]
/Users/justin/Workspace/CMS-of-Blog/server/api.js:28
  const {name, pwd} = req.body
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/justin/Workspace/CMS-of-Blog/server/index.js:9:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/justin/.nvm/versions/node/v5.0.0/bin/node" "/Users/justin/.nvm/versions/node/v5.0.0/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! CMS2@2.1.1 start: `node ./server/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CMS2@2.1.1 start script 'node ./server/index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the CMS2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server/index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs CMS2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls CMS2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justin/Workspace/CMS-of-Blog/npm-debug.log

======

I got this error after run npm start

**Comment by Justinnng** [comment]
sorry, it's my node version problem. update node version, it's fixed
