### ISSUE TITLE
"npm run dev " not work   

### ISSUE THREAD

**Issue by williamjie** [ycwalker/CMS-of-Blog#5]
> CMS2@2.1.1 dev /Users/zj/Documents/company_code/CMS-of-Blog
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot

/Users/zj/Documents/company_code/CMS-of-Blog/node_modules/cross-env/dist/index.js:58
  var envVars = Object.assign({}, process.env);
                       ^
TypeError: undefined is not a function
    at getCommandArgsAndEnvVars (/Users/zj/Documents/company_code/CMS-of-Blog/node_modules/cross-env/dist/index.js:58:24)
    at crossEnv (/Users/zj/Documents/company_code/CMS-of-Blog/node_modules/cross-env/dist/index.js:22:35)
    at Object.<anonymous> (/Users/zj/Documents/company_code/CMS-of-Blog/node_modules/cross-env/bin/cross-env.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 16.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! CMS2@2.1.1 dev: `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CMS2@2.1.1 dev script 'cross-env NODE_ENV=development webpack-dev-server --open --inline --hot'.
npm ERR! This is most likely a problem with the CMS2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --open --inline --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls CMS2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zj/Documents/company_code/CMS-of-Blog/npm-debug.log

**Comment by williamjie** [comment]
my env was wrong ????

**Comment by ciqulover** [comment]
node version > 6 & npm version >3

**Comment by williamjie** [comment]
多谢，升级node 以及npm 解决问题
